version: "3.1"

services:
  mongo:
    hostname: mongo
    image: mongo:7.0.0-rc8
    command: mongod --port ${MONGO_PORT}
    restart: always
    volumes:
      - ./data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 27017:${MONGO_PORT}
    networks:
      - mongo_net

  backend:
    hostname: backend
    env_file:
      - backend.env
    environment:
      - DB_HOST=mongo
      - DB_PORT=${MONGO_PORT}
      - DB_USERNAME=${MONGO_USERNAME}
      - DB_PASSWORD=${MONGO_PASSWORD}
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./data/images:/app/public
    depends_on:
      - mongo
    networks:
      - mongo_net
      - nginx_net

  frontend:
    hostname: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - INVOICE_DATA_API_URL=${INVOICE_DATA_API_URL}
        - INVOICE_DATA_API_TOKEN=${INVOICE_DATA_API_TOKEN}
        - BACKEND_URL=https://${SERVER_HOST}/api/v1
        - BASE_LOCATION=/invoice-collection
    restart: on-failure
    volumes:
      - ./nginx/frontend:/etc/nginx/conf.d
    networks:
      - nginx_net

  nginx:
    image: nginx:1.25.1-alpine3.17-slim
    restart: on-failure
    volumes:
      - ./nginx/web-server/root:/var/www/html
      - ./nginx/web-server/conf.d:/etc/nginx/conf.d
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt
      - ./dhparam:/etc/ssl/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend
    networks:
      - nginx_net
  
  certbot:
    image: certbot/certbot:v2.6.0
    volumes:
      - ./nginx/web-server/root:/var/www/html
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email nyaneet@icloud.com --agree-tos --no-eff-email --force-renewal -d cyberbruhers.xyz -d www.cyberbruhers.xyz
  
networks:
  mongo_net:
    driver: bridge
  nginx_net:
    driver: bridge
