version: "3"
services:
    backend:
        hostname: backend
        build: ./backend/
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: kavun
        ports:
            - 8080:8080
        volumes:
            - ./backend/:/app/
        restart: on-failure
        networks:
            - postgres_net
            - backend_net

    postgres:
        image: 15.2-alpine3.17
        hostname: postgres
        environment:
            POSTGRES_PASSWORD: kavun
        restart: on-failure
        networks:
            - postgres_net
networks:
    backend_net:
        driver: bridge
    postgres_net:
        driver: bridge