version: "3"
services:
    backend:
        hostname: backend
        build: ./backend/
        environment:
            DB_HOST: invoices_db
            DB_USER: postgres
            DB_PASSWORD: kavun
            DB_NAME: invoices_meta
        ports:
            - 8080:8080
        volumes:
            - ./backend/static/:/app/static/
        restart: on-failure
        networks:
            - postgres_net
            - backend_net

    invoices_db:
        image: postgres:15.2-alpine3.17
        hostname: invoices_db
        environment:
            POSTGRES_PASSWORD: kavun
        volumes:
            - ./database/init_scripts/:/docker-entrypoint-initdb.d/:ro
        restart: on-failure
        networks:
            - postgres_net
networks:
    backend_net:
        driver: bridge
    postgres_net:
        driver: bridge